name: Build and Publish Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
env:
  VERSION_MAJOR: 1
  VERSION_MINOR: 0
  VERSION_SNAPSHOT_FILENAME: sample-app
  SNAPSHOT_NAME_PREFIX: Winter23_S15B1

jobs:

  build-deploy:
    runs-on: ubuntu-latest
    env:
      component_name: deploy
    outputs:
      version: ${{env.component_name}}-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{ github.run_number }}
      artifact-url: ${{ steps.publish_artifact.outputs.artifact-url }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Publish Artifact
        id: publish_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.component_name}}-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{ github.run_number }}
          path: ${{env.component_name}}
          retention-days: 90


  build-web1:
    runs-on: ubuntu-latest
    env:
      component_name: web1
    outputs:
      version: ${{env.component_name}}-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{ github.run_number }}
      artifact-url: ${{ steps.publish_artifact.outputs.artifact-url }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Publish Artifact
        id: publish_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.component_name}}-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{ github.run_number }}
          path: ${{env.component_name}}
          retention-days: 90


  build-web2:
    runs-on: ubuntu-latest
    env:
      component_name: web2
    outputs:
      version: ${{env.component_name}}-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{ github.run_number }}
      artifact-url: ${{ steps.publish_artifact.outputs.artifact-url }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Publish Artifact
        id: publish_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.component_name}}-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{ github.run_number }}
          path: ${{env.component_name}}
          retention-days: 90


  build-web3:
    runs-on: ubuntu-latest
    env:
      component_name: web3
    outputs:
      version: ${{env.component_name}}-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{ github.run_number }}
      artifact-url: ${{ steps.publish_artifact.outputs.artifact-url }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Publish Artifact
        id: publish_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.component_name}}-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{ github.run_number }}
          path: ${{env.component_name}}
          retention-days: 90

  create-snapshot:
    runs-on: ubuntu-latest
    # if: ${{ always() }}
    needs: [build-deploy, build-web1, build-web2, build-web3]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: thfai2000/version_snapshots
          token: ${{ secrets.GH_PAT }}
          ref: main

      - name: Create Versions Snapshot
        run: |

          ./utils/update_latest_snapshot.sh ${{ env.VERSION_SNAPSHOT_FILENAME }} deploy ${{ needs.build-deploy.outputs.version }} ${{ github.sha }} ${{ needs.build-deploy.outputs.artifact-url }}

          ./utils/update_latest_snapshot.sh ${{ env.VERSION_SNAPSHOT_FILENAME }} web1 ${{ needs.build-web1.outputs.version }} ${{ github.sha }} ${{ needs.build-web1.outputs.artifact-url }}

          ./utils/update_latest_snapshot.sh ${{ env.VERSION_SNAPSHOT_FILENAME }} web2 ${{ needs.build-web2.outputs.version }} ${{ github.sha }} ${{ needs.build-web2.outputs.artifact-url }}

          ./utils/update_latest_snapshot.sh ${{ env.VERSION_SNAPSHOT_FILENAME }} web3 ${{ needs.build-web3.outputs.version }} ${{ github.sha }} ${{ needs.build-web3.outputs.artifact-url }}
        
          ./utils/create_snapshot.sh ${{ env.VERSION_SNAPSHOT_FILENAME }} ${{ env.SNAPSHOT_NAME_PREFIX }}

          git config user.email "${{ env.VERSION_SNAPSHOT_FILENAME }}@example.com"
          git config user.name "${{ env.VERSION_SNAPSHOT_FILENAME }}"
          git add .
          git commit -m "Create/Update Snapshot ${{ env.SNAPSHOT_NAME_PREFIX }}"
          git push
        
      # - name: Trigger Ansible Tower Job
      #   run: |
      #     curl -X POST -H "Content-Type: application/json" \
      #     -u USERNAME:PASSWORD \
      #     -d '{"extra_vars": {"artifact": "my-artifact"}}' \
      #     https://ansible-tower/api/v2/job_templates/123/launch/